#!/bin/sh
#. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Odoo Workers CPU Usage'
    echo 'graph_vlabel %'
    echo 'graph_scale no'
    echo 'graph_category odoo'
    echo 'graph_info This graph shows the CPU usage of Odoo workers'
    echo 'total.label Total'
    echo 'max.label Maximum'
    echo 'avg.label Average'
    echo 'total.warning 2400'
    echo 'total.critical 2800'
    exit 0
fi

#odoo='./server/8.0/openerp'
odoo='proj80'
tmp='/tmp/topodoo'
top -b -n 1 | grep "$odoo" | grep python > $tmp
# total workers CPU usage
total=`awk '{cpu+=$9}; END {print cpu}' $tmp`

# max worker CPU usage
max=`awk 'BEGIN {max=0;} {if ($9>max) {max=$9}} END {print max}' $tmp`

# average worker CPU usage
avg=`awk '{ sum += $9 } END { if (NR > 0) print (sum / NR) }' $tmp`

echo "total.value $total"
echo "max.value $max"
echo "avg.value $avg"
#echo "killed.value 0"
