#!/bin/sh
#. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo graph_args --logarithmic --units=si
    echo 'graph_title Odoo Workers Memory Usage'
    echo 'graph_vlabel Bytes'
    echo 'graph_category odoo'
    echo 'graph_info This graph shows the memory usage of Odoo workers'
    echo 'total.label Total'
    echo 'max.label Maximum'
    echo 'avg.label Average'
    exit 0
fi

odoo='odoo-bin\|openerp\|odoo\.py'
# total workers memory usage
#total=`ps -eo 'rss,command' | grep "$odoo" | grep -v grep | awk '{mem+=int($1*1024)}; END {print mem}'`

# max worker memory usage
#max=`ps -eo 'rss,command' | grep "$odoo" | grep -v grep | awk 'BEGIN {max=0;} {if ($1>max) {max=$1}} END {print max*1024}'`

# average worker memory usage
#avg=`ps -eo 'rss,command' | grep "$odoo" | grep -v grep | awk '{ sum += $1 } END { if (NR > 0) printf "%.0f",(sum / NR)*1024 }'`

ps -eo 'rss,command' | grep "$odoo" | grep -v grep | awk 'BEGIN {sum=0;max=0;avg=0;} {sum+=$1; if ($1>max) max=$1;} END {if (NR>0) avg=sum/NR; printf "total.value %d\nmax.value %d\navg.value %d\n", sum*1024, max*1024, avg*1024}'

#echo "total.value $total"
#echo "max.value $max"
#echo "avg.value $avg"
