#!/bin/sh
#. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Odoo Workers Usage'
    echo 'graph_vlabel worker'
    echo 'graph_category odoo'
    echo 'graph_info This graph shows the usage of Odoo workers'
    #echo 'total.label Total'
    echo 'busy.label Busy'
    echo 'idle.label Idle'
    echo 'busy.draw AREA'
    echo 'idle.draw STACK'
    echo 'idle.colour COLOUR6'
    echo 'busy.colour COLOUR7'
    echo 'killed.label Killed'
    echo 'killed.draw LINE'
    echo 'killed.colour COLOUR1'
    #echo 'busy.warning 20'
    #echo 'total.critical 640'
    echo 'killed.warning 1'
    echo 'killed.critical 3'
    exit 0
fi

odoo='odoo\|openerp'
# busy worker when STATE is D or R
busy=`ps -eo 'stat,command' | grep "$odoo" | cut -b 1 | grep 'D\|R' | wc -l`

# idle worker when STATE is S
idle=`ps -eo 'stat,command' | grep "$odoo" | cut -b 1 | grep 'S' | wc -l`

# worker killed by kernel (out of memory)
srvname='openerp-server80'
tgl=`echo "$(date +'%F')"`
killed=`journalctl -u "$srvname" --since="$tgl" | grep 'python invoked oom-killer' | wc -l`

#echo "total.value $total"
echo "busy.value $busy"
echo "idle.value $idle"
echo "killed.value $killed"
