#!/bin/sh
#. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo graph_args --logarithmic --units=si
    echo 'graph_title Odoo Workers CPU Usage'
    echo 'graph_vlabel %'
    echo 'graph_scale no'
    echo 'graph_category odoo'
    echo 'graph_info This graph shows the CPU usage of Odoo workers'
    echo 'total.label Total'
    echo 'max.label Maximum'
    echo 'avg.label Average'
    exit 0
fi

odoo='odoo-bin\|openerp\|odoo\.py'
# total workers CPU usage
#total=`ps -eo 'pcpu,command' | grep "$odoo" | grep -v grep | awk '{cpu+=$1}; END {print cpu}'`

# max worker CPU usage
#max=`ps -eo 'pcpu,command' | grep "$odoo" | grep -v grep | awk 'BEGIN {max=0;} {if ($1>max) {max=$1}} END {print max}'`

# average worker CPU usage
#avg=`ps -eo 'pcpu,command' | grep "$odoo" |  grep -v grep |awk '{ sum += $1 } END { if (NR > 0) print (sum / NR) }'`

ps -eo 'pcpu,command' | grep "$odoo" | grep -v grep | awk 'BEGIN {sum=0;max=0;avg=0;} {sum+=$1; if ($1>max) max=$1;} END {if (NR>0) avg=sum/NR; printf "total.value %d\nmax.value %d\navg.value %d\n", sum, max, avg}'

#echo "total.value $total"
#echo "max.value $max"
#echo "avg.value $avg"
